### ISSUE TITLE
[Feature] Inter-Hexen: Autoload support for hexdd.wad

### ISSUE THREAD

**Issue by NightFright2k19** [JNechaevsky/international-doom#104]
Inter-Hexen apparently won't load assets placed in the autoloads\hexdd.wad subdir. For those who want to use widescreen assets (even if it's mostly just the title pic), it would be nice to have.

**Comment by JNechaevsky** [comment]
Gladly implemented in https://github.com/JNechaevsky/international-doom/commit/95c1f1ca16d7474b18933f6a7b5ab38aa81f0e36, kind thanks for suggestion!

**Comment by NightFright2k19** [comment]
Appreciated. 

Just for the record: In general, Inter-Doom does not support autoload directories for pwads like Crispy, right? Asking because I have some fixes for the Doom II Master Levels which are residing in subdirs like attack.wad, blacktwr.wad and so on.

**Comment by JNechaevsky** [comment]
Yeah, that's right. There was never PWAD autoloading in Doom, but when I have added it into Heretic and spent about two weeks trying different test wads, and accidently took a look at `autoload` folder... In short words, I wasn't very happy to see all my stuff was created as autoload folders, and hell, I never asked for auto creating folders like "herpln, herdamn, herspr, hersunder15, hernuts, ..." . Since then, PWAD file disabled with [comment](https://github.com/JNechaevsky/international-doom/blob/main/src/heretic/d_main.c#L1089-L1090).
