### ISSUE TITLE
[Heretic] End screen of E3M8 doesn't scroll properly

### ISSUE THREAD

**Issue by kitchen-ace** [JNechaevsky/international-doom#43]
Very minor bug: when you beat Heretic's E3M8, after the text screen there's a two-part graphic that is supposed to scroll up. In inter-heretic it simply jumps from the bottom graphic to the top. Also if "text casts shadows" is enabled, during the time that the screen should be scrolling, the shadows flicker.

Here's a wad that makes it easier to test, on E3M8, just step forward to exit. End text message is replaced with just `.`

[e3m8h.zip](https://github.com/JNechaevsky/international-doom/files/13891207/e3m8h.zip)

**Comment by JNechaevsky** [comment]
Oh no, that's my second favorite thing to break after `ENDOOM` screens. 🙈 Once render was updated to support 3x, 5x and 6x resolution, previous RAW screen drawing function was no longer working, and @rfomin wrote an updated function to support any resolution. It is working perfectly for static RAWs scrolling from-top-to-bottom (lower demon's half), but at the moment don't know how to draw from bottom-to-top (upper demon's half). I still haven't investigated how to do this, but this most likely an dead end for me.

**Comment by kitchen-ace** [comment]
>Oh no, that's my second favorite thing to break after ENDOOM screens.

Haha, sorry! It's a very, very minor issue anyhow.

**Comment by JNechaevsky** [comment]
I've left a [comment here](https://github.com/JNechaevsky/international-doom/blob/main/src/heretic/f_finale.c#L278 ) for better ~~tomorrow~~ feature. 🙂 To get first scrolling screen working, just uncomment [these lines](https://github.com/JNechaevsky/international-doom/blob/main/src/heretic/f_finale.c#L291-L295).

Skipable finale screens are also possible, and it's on the list. I did in old Inter-Heretic version, but I would like review/update it here, on same manner as in current Doom, where `finaletics` are not increased by magical value, but for exactly necessary ammount + small extra tics for robustness.

**Comment by Meerschweinmann** [comment]
Someone noticed and reported before me. Good to know it's a known issue :)

**Comment by JNechaevsky** [comment]
This is not an issue, this is literally whole damn final boss of this project. And I can't handle it. 🙁 Scrolling down coords are working on paper, but no luck getting it work in the code. My only choice left is to ask for help.

Aside from this, everything seems to be almost done, just a few things left:
- Screen border is not properly updated beneath bottom KIS and ammo widgets, leaving some pixel remainings from these widget. Not very critical if border is not used, but should be fixed careful way somehow.
- Not sure if XYZ sound attenuation will work properly on extreme complex maps, some distance overflow probably may happen. Not critical, but because of such overflow object's sound my appear like it's nearby while, in fact, object is in another half of the universe. Not tested yet, just a thought.
- There was small change in Crispy Heretic regarding mouse look handling for demos. 🤔

**Comment by kitchen-ace** [comment]
>There was small change in Crispy Heretic regarding mouse look handling for demos. 🤔

Interesting, can you point me to the commit? I don't see it at a glance.

**Comment by JNechaevsky** [comment]
> Interesting, can you point me to the commit? I don't see it at a glance.

Must be [this one](https://github.com/fabiangreffrath/crispy-doom/commit/dd3caf4df99d6bb3ea47cc338b3c19e547797c54), but looks likes I have already merged it.
