### ISSUE TITLE
Hexen: torch goes too dark

### ISSUE THREAD

**Issue by kitchen-ace** [JNechaevsky/international-doom#73]
When you use the torch, it's supposed to make the level bright, and oscillate the light level a bit. In inter-hexen the light oscillates way too far, with the lowest value being pretty dark. 

Also affects crispy-hexen, but only truecolor builds.

**Comment by JNechaevsky** [comment]
So that's how most useful artifact decided to remind about itself. 😦 Thank you for pointing out, I have to investigate what is happening.

**Comment by JNechaevsky** [comment]
@kitchen-ace, @Meerschweinmann, @NightFright2k19,

While we here, there is one templating thing to do, but I would like to ask for your opinions. Here's how torch working in vanilla:

https://github.com/JNechaevsky/international-doom/assets/21193394/b895ce69-aba5-45bd-b51c-411c4fb79544

See? It's like a... Sequence of lighting changes, then sequence of stable lighting. If "stable lighting" sequence will be removed, then animation will looks like this:

https://github.com/JNechaevsky/international-doom/assets/21193394/3d766c6d-d95d-48fd-8a0e-eb0c85a13a90

Somehow it feels more realistic or smooth, and such correction must be demo-safe. It you wish to try out, just replace this like:
```
        else if (!(leveltime & 16) && player == &players[consoleplayer])
```
With:
```
        else if (player == &players[consoleplayer])
```
In [Heretic](https://github.com/JNechaevsky/international-doom/blob/main/src/heretic/p_user.c#L810C1-L810C73) and [Hexen](https://github.com/JNechaevsky/international-doom/blob/main/src/hexen/p_user.c#L981) respectively, and then recompile executables.

And just in case `git pull` will be unhappy after changes, just reset sources to git-friendly using `git reset --hard` command.

**Comment by Meerschweinmann** [comment]
Depending on how many and which sort of wood i throw in my oven, my living rooms lightening is like Hexen Vanilla lighting or your new unstable lighting. So both types are realistic in my opinion 😀

Both types look good.

When i am home i will have a "live" look.

**Comment by kitchen-ace** [comment]
I actually find that change oddly uncomfortable. It looks nice as an effect, but playing with it or even watching that video is kind of unpleasant for me.

**Comment by Meerschweinmann** [comment]
I have tested both versions on several displays.

One thing i did not notice on my display at work with the minimized videos was, on brighter displays the vanilla lightning is more pleasant as it does not change so fast between darker and brighter.

Sure in reality with a torch and some wind the non-vanilla version is more realistic, but on big bright screens i feel it very hectic.
So i would prefer the vanilla version.

Or, if it is not too much work, as an option in the menu.

**Comment by JNechaevsky** [comment]
That's was a really extensive test, thank you both!

So, it is obliviously a no-go then. Yesterday I have checked it in a tiny game window (day job, after all), but later in the evening tried it out on a big monitor. Yeah, it feels incorrect, probably too intensive light changing. It could be useful for some kind of custom sector effect, but it's out of scope for vanilla specifics. And as Fabian would say: _"If unsure or in doubts, use vanilla approach then"._

As about menu option - better to avoid such micro-switches by all costs, I made a lot of such mistakes (i.e. "features for features") in 6.x versions of the port, and definitely don't want to repeat it again. Because of this, few cools small things are missing:

- All attacks (hitscans and missiles) are making splashes of liquids in Heretic.
- Falling leafs from brown trees are affected by flowing liquids effect and may literally drown in Hexen.

Despite of being cool things, both of these are making small unoptional changes in game mechanics, even by being guarded to "single player only" to prevent demo/netgame desyncs. Maybe one day in the feature it will be worth to revisit such improvement and place them into "Cosmetical" gameplay section, but really not now.

**Comment by Meerschweinmann** [comment]
"If unsure or in doubts, use vanilla approach then", wise words from Mr. Greffrath :)
Something similar i wanted to say yesterday, but was not sure how to say it in english. Both lighting versions have their pros and cons. Someone likes this more, the other that. 
Inter-DOOM is part of the faithful DOOM ports. So you can say it is vanilla behavior and you have a reason why you have done it this way.

And if an option brings demo or netgame desyncs and can only be used in certain cirumstances it is probably not really worth it.

For those who want to mod ID-Tech1 games far beyond what ID-Tech1 games could do, there is GZDOOM.

**Comment by Meerschweinmann** [comment]
That looks good to me, even with the cute pig 😀

**Comment by NightFright2k19** [comment]
A very good and functional HUD. I rarely play fullscreen in vanilla ports, but I'm digging it, anyway.
