### ISSUE TITLE
Inter-DOOM mouse-look option

### ISSUE THREAD

**Issue by Meerschweinmann** [JNechaevsky/international-doom#79]
Helloho,

Inter-Heretic and Inter-Hexen both have a mouse-look option in "control-settings".
To use mouse-look in Inter-DOOM i assign a key for the mouse-look toggle under key-bindings and press that key once, or edit the config file.

That was never a problem, because i have a backup of my config-files that i copy in the folder, but for newcomers or the sake of equality Inter-DOOM should handle it like the other both games.

**Comment by JNechaevsky** [comment]
Good evening! 🙂

It wasn't previously added because of one extra line will be slightly placed on sacred status bar:
![image](https://github.com/JNechaevsky/international-doom/assets/21193394/6260dd89-13a7-40e1-87a0-6b7def60a2f2)

But I still can move up this whole menu one line up, just like it is done with Display options. Will merge changes soon.

**Comment by Meerschweinmann** [comment]
That would be a sin to touch the sacred status bar :)
