### ISSUE TITLE
[Bug] Inter-Hexen: "Randomly Mirrored Corpses" menu option too long

### ISSUE THREAD

**Issue by NightFright2k19** [JNechaevsky/international-doom#84]
In Inter-Hexen, the new option for "Randomly Mirrored Corpses" seems to be too long in the menu to show which selection you have actually made. 

I guess the solution would be to either make the option name shorter (e.g. "Mirrored Corpses") or increase the distance between option names and choices.

**Comment by JNechaevsky** [comment]
Honestly, I'd prefer to leave this name as is, as it was used in all version all the time. Also, it's length is not a problem, since there will be only "on/off". Increasing distance is possible, just need to make sure that "next ..." and "1/2" elements will align good with status bar's life and A.C. squares.

Real problem was with "Assembled weapon widget", so it is shortened to "4th weapon widget". Otherwise this will happen:
![image](https://github.com/JNechaevsky/international-doom/assets/21193394/9213414a-c969-46bd-b328-173d49c50c81)

**Comment by JNechaevsky** [comment]
From another hand, should menu get's wider, then asteriks symbol will be drawn on top of demon's ear or head.
![image](https://github.com/JNechaevsky/international-doom/assets/21193394/2602e42e-e66d-4abe-922d-866dbdebd60f)

I have to be very careful, moving for `3` pixels is OK to align with vertical spine bone, so it will be like this:
![image](https://github.com/JNechaevsky/international-doom/assets/21193394/b7b32793-94a8-419d-9d22-9b0e4904bdc6)

But most likely, it doesn't really not needed such pixel surgery.

**Comment by NightFright2k19** [comment]
Well, main thing is one can verify the choice through the menu again. Right now, I can only see "Randomly Mirrored Corpses" and that's it. :)

**Comment by JNechaevsky** [comment]
Yep, there is no choice because the feature itself is not there yet, it's WIP. Will be done today, soon I hope. 🙂

**Comment by NightFright2k19** [comment]
Ah, now I understand. I was confused since the cvar already exists, so my assumption was something was wrong with the menu. False alarm, then. ^^
