### ISSUE TITLE
[Bug] HEHACKED (partially) not working

### ISSUE THREAD

**Issue by NightFright2k19** [JNechaevsky/international-doom#86]
It seems that at least some parts of an embedded HEHACKED lump suddenly aren't recognized any more in Inter-Heretic. Used to work fine in earlier builds.

The following code will only show the level names, but not the episode (in this case, ep.1):
```
Patch File for HHE v1.1

# Note: Use the pound sign ('#') to start comment lines.

Heretic version = 10
Patch format = 1

Text 7096 21
DUNGEONS AND MONSTERS

Text 1240 30
E1M1:  DUNGEONS AND MONSTERS 1

Text 1260 30
E1M2:  DUNGEONS AND MONSTERS 2

Text 1280 30
E1M3:  DUNGEONS AND MONSTERS 3

Text 1304 30
E1M4:  DUNGEONS AND MONSTERS 4

Text 1328 30
E1M5:  DUNGEONS AND MONSTERS 5

Text 1348 30
E1M6:  DUNGEONS AND MONSTERS 6

Text 1372 30
E1M7:  DUNGEONS AND MONSTERS 7

Text 1392 30
E1M8:  DUNGEONS AND MONSTERS 8

Text 1412 30
E1M9:  DUNGEONS AND MONSTERS 9
```

Tested with various other files, same result. So far, episode names are the only thing I can confirm to be malfunctioning.

**Comment by JNechaevsky** [comment]
Done! Hehackedization (oh my that word!) of vanilla menus/string did not survived recent menu highlighting improvement. Now it's back, thanks for pointing out!

**Comment by NightFright2k19** [comment]
Confirmed, works again. ^^ Guess that's what sometimes happens when one is on fire programming like crazy. Stuff starts burning which shouldn't. But that's why there are guys like me who tell you where the fires are. Before they spread. Following Romero's credo: "Fix your bugs. The longer you wait, the worse they get."

**Comment by JNechaevsky** [comment]
First of all, if you, @kitchen-ace and @Meerschweinmann didn't helped a lot with every aspects all this time, things should go much, much harder. I sometimes asking myself: _"Why I'm digging it so hard?"_, and despite of being able to find few self-explanations, none of them can answer _"Why exactly"_. There is an English word "dedication", and looks likes it explains everything well. 

Another thing is - I'm pretty introvert-egocentristic person, but never turning it into some kind of silly childish ambitions like "ha-ha, I can do this, I can do that, I, I, I!!!" and always trying to be polite. Especially with the persons who helping me and who have interest for this project, who find it interesting! And when such persons are encountering any kind of bugs or inconveniences, egocentrism doing it's job right, like: "I did something wrong and valuable persons suffer it, I must fix it ASAP to make them happy again".

Something like this, don't get it too straight, it's mostly a philosophical thing. 🙂 My fads must remain my fads, and what is really matters is quality.

**Comment by Meerschweinmann** [comment]
Heyho, i am happy to help or motivate as far as i can 😊 On the other hand you make many people inclusive me happy to experience DOOM, Heretic and Hexen in a faithful enhanced way on todays hardware. And believe me, i was very very happy as i saw that Heretic and later Hexen came back as it was at RD/earlier ID times, but even better.
And you are a communicative, helpful and nice person. So everything is fine for me and a reason why i like to look here 😀
You seem to have fun too in doing what you do, so everything is perfect.

**Comment by kitchen-ace** [comment]
I'm also glad I can help. I hope you do this for yourself most of all though, it's important that when your working so hard on this it's because your getting something out of it. But it seems like you are, and you can take pride in the result.

That said, Crispy Heretic was never *quite* full-featured enough for me to be totally happy with it; inter-heretic is pretty much my dream Heretic port, and I've been playing through Heretic wads a ton since you first brought it back, so I'm immensely happy and grateful for all you've done with it!

**Comment by Meerschweinmann** [comment]
Another addition to what kitchen-ace said to Heretic. It's a Crispy-Heretic on steroids. 
Which ports are out there that feature software rendered truecolor with resolutions up to 6x, brightmaps, mirrored corpses, swirling flats... and vanilla demo compatibility? As far as i know Inter-Heretic and Inter-Hexen have with this feature set here a unique selling point (Hope that word ist correct).

**Comment by JNechaevsky** [comment]
Thanks for the kind words of support. That's the only and best motivation to keep things going, that's really all what is needed! 🙇🏻‍♀️

Heretic seems to be polished well, and it is unbelievable, but Hexen is just [two weeks old](https://github.com/JNechaevsky/international-doom/commit/70de17960d816ec5c966e594d25d699de3f3696f) at this point, but have almost everything needed. This is insane. 🤓 Nothing ground-breaking though, the code from Doom and Heretic helped a lot, so everything going pretty well. 

There are couple of Hexen-TODO thoughts:

* Sector special `200` (use second sky on sector with `200` special) is not working in Hexen properly. I.e. it's working on floors, but not in ceilings due to a bug. It was [investigated](https://www.doomworld.com/forum/topic/140899-hexen-sector-special-200-alternate-sky/) by andrewj and @kitchen-ace, easy to fix, but the question is - is it needed? None of vanilla Hexen or DK maps are using such sky. Probably just for some possible mods support?

* There is a bug in vanilla Hexen, when throwed flechettes are bumping to glitter bridge and falling to extreme tall sector. It is possible to fix, but it's a play state thing, it will affect all possible occurrences, not flechettes only. It can be guarded by "single player" only condition, but I no longer going this way, so game mechanics always working in "one logics", matters no is it single player or multiplayer game. And yes, it crashed Crispy and DSDA too, so probably left it "as is"...

https://github.com/JNechaevsky/international-doom/assets/21193394/7323d66f-6193-4d36-bd4b-d3af225d8a15

* Hexen wants demo footer and demo-XXXXX prefix to prevent demo file overwriting. 

* Rotation of glitter bridge (three rotating stars) could be more smooth. But I must be 200% sure that it won't break demos, as it's play state thing...

* Random flipping of blood sprites, puffs, water/lava/sludge splashes.

* What about disappearing puffs on Hexen? It happens, but again, must be 200% sure that fixing will be safe for demos, like in Doom and Heretic.

**Comment by JNechaevsky** [comment]
> Sector special 200 (use second sky on sector with 200 special) is not working in Hexen properly.

Well, fix it's not that trivial.. 😀 Because this way all sector specials will be applied to ceiling as well, notably scrolling effects.



https://github.com/JNechaevsky/international-doom/assets/21193394/61107b94-8a3c-47d4-8e53-945e3e465ac2

**Comment by kitchen-ace** [comment]
Sector special 200: should be easy enough to special-case the ceilingplane special in r_bsp.c [here](https://github.com/JNechaevsky/international-doom/blob/main/src/hexen/r_bsp.c#L474) with something like 
`frontsector->lightlevel, (frontsector->special = 200) ? 200 : 0): NULL;` (untested).

Is it worth it? It probably doesn't hurt anything, but that's also the kind of feature that if you're using you really want to have working in all ports. I don't know if MBF sky transfers would be possible/easier? I'll test some things in dsda-doom to see what it does, when I can.


>throwed flechettes are bumping to glitter bridge and falling to extreme tall sector

Pretty edge case bug, and since it affects demo compatibility, something that you can leave.


>Rotation of glitter bridge (three rotating stars) could be more smooth

Would look nice but only if it's easy to do while staying demo-compatible; they don't pop up that much, and they don't look bad as-is


>What about disappearing puffs on Hexen? 

There aren't really any hitscan weapons in Hexen, and explosions disappearing in the sky or whatever isn't even that common.
