### ISSUE TITLE
[Bug] Inter-Hexen compilation errors (demo-related)

### ISSUE THREAD

**Issue by NightFright2k19** [JNechaevsky/international-doom#91]
Looks like more compilation errors have been introduced with latest commits, I'm afraid...

```
FAILED: src/hexen/CMakeFiles/hexen.dir/mn_menu.c.obj
international-doom/src/hexen/mn_menu.c: In function 'MN_Responder':
international-doom/src/hexen/mn_menu.c:4899:31: error: 'netdemo' undeclared (first use in this function)
 4899 |         else if ((!netgame || netdemo) && key != 0 && key == key_reloadlevel)
      |                               ^~~~~~~
international-doom/src/hexen/mn_menu.c:4899:31: note: each undeclared identifier is reported only once for each function it appears in
international-doom/src/hexen/mn_menu.c:4910:17: warning: implicit declaration of function 'G_DoPlayDemo'; did you mean 'G_PlayDemo'? [-Wimplicit-function-declaration]
 4910 |                 G_DoPlayDemo();
      |                 ^~~~~~~~~~~~
      |                 G_PlayDemo

```

**Comment by JNechaevsky** [comment]
Just a moment, I'm almost done with it.

**Comment by JNechaevsky** [comment]
All done, fixed in https://github.com/JNechaevsky/international-doom/commit/fd144c2877faac2dfbaa780055b3db856f017f58. There is something odd with going to next level while non demo playback, there is a notable delay. I don't understand what is happening, either querying `MAPINFO` is slow as hell, or there is some kind of internal delay, this will need some investigation, but technically it's working now.

**Comment by JNechaevsky** [comment]
Ah, no, it's not a special delay. When player goes to next level, game makes an autosave which is a bit expensive in Hexen. Guess, probably better leave it as-is, going to next level is not something very useful while normal playing (not demo playback).

**Comment by NightFright2k19** [comment]
Beautiful. Compiler is compiling again. Great work! ^^
